import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { type Cookie, session } from "electron";
import log from "electron-log/main.js";

const PARTITION = "persist:pond-scrapers";

const COOKIE_HOSTS = [
  "https://x.com/",
  "https://twitter.com/",
  "https://www.instagram.com/",
  "https://instagram.com/",
  "https://www.cosmos.so/",
  "https://cosmos.so/",
  "https://www.tiktok.com/",
  "https://tiktok.com/",
  "https://www.youtube.com/",
  "https://youtube.com/",
  "https://m.youtube.com/",
] as const;

export interface CookieJar {
  path: string;
  cleanup: () => Promise<void>;
  count: number;
}

export async function writeNetscapeCookies(): Promise<CookieJar> {
  const dir = await mkdtemp(join(tmpdir(), "pond-ytdlp-"));
  const filePath = join(dir, "cookies.txt");
  const cleanup = async () => {
    try {
      await rm(dir, { recursive: true, force: true });
    } catch (err) {
      log.warn("[pond cookies] cleanup failed", dir, err);
    }
  };

  let allCookies: Cookie[] = [];
  try {
    const persistent = session.fromPartition(PARTITION);
    const buckets = await Promise.all(
      COOKIE_HOSTS.map((url) =>
        persistent.cookies.get({ url }).catch(() => [] as Cookie[]),
      ),
    );
    const seen = new Set<string>();
    for (const bucket of buckets) {
      for (const c of bucket) {
        const key = `${c.domain ?? ""}|${c.name}|${c.path ?? "/"}`;
        if (seen.has(key)) continue;
        seen.add(key);
        allCookies.push(c);
      }
    }
  } catch (err) {
    log.warn("[pond cookies] enumerate failed; writing empty jar", err);
    allCookies = [];
  }

  const lines = [
    "# Netscape HTTP Cookie File",
    "# Generated by pond — do not edit manually.",
    "",
  ];
  for (const c of allCookies) {
    const line = formatNetscapeLine(c);
    if (line) lines.push(line);
  }
  await writeFile(filePath, `${lines.join("\n")}\n`, "utf8");

  return { path: filePath, cleanup, count: allCookies.length };
}

function formatNetscapeLine(c: Cookie): string | null {
  if (!c.name || c.value === undefined) return null;
  const domain = c.domain ?? "";
  if (!domain) return null;
  const includeSubdomains = domain.startsWith(".") ? "TRUE" : "FALSE";
  const path = c.path ?? "/";
  const secure = c.secure ? "TRUE" : "FALSE";
  const expires = c.expirationDate
    ? Math.floor(c.expirationDate)
    : c.session
      ? 0
      : Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 30;
  const safeName = sanitise(c.name);
  const safeValue = sanitise(c.value);
  if (!safeName || safeValue === null) return null;
  return [
    domain,
    includeSubdomains,
    path,
    secure,
    String(expires),
    safeName,
    safeValue,
  ].join("\t");
}

function sanitise(s: string): string | null {
  if (s == null) return null;
  if (s.includes("\n") || s.includes("\r") || s.includes("\t")) return null;
  return s;
}
