import { useEffect, useRef, useState } from "react";
import { recordAspect } from "@/pages/saves-view/aspect";
import { useCardContext } from "./context";
import styles from "./styles.module.css";

export function Image() {
  const { state } = useCardContext();
  if (!state.unit || state.unit.isVideo || state.isBroken) return null;
  // Inner subcomponent + URL key so the loaded/transition state
  // resets cleanly when the picked unit URL flips (heal, re-import).
  return <ImageInner key={state.unit.url} />;
}

function ImageInner() {
  const { state, actions } = useCardContext();
  const ref = useRef<HTMLImageElement>(null);
  const [loaded, setLoaded] = useState(false);

  const url = state.unit?.url ?? "";
  const cover = state.save.files[state.save.coverIndex ?? 0];
  const w = cover?.width ?? state.save.width ?? undefined;
  const h = cover?.height ?? state.save.height ?? undefined;
  const blur = state.save.blurDataUrl ?? null;
  const tint = state.save.dominantColors?.[0]?.hex;

  // Cached images can complete before React attaches the load
  // handler — common when scrolling back through cards we've already
  // rendered. Without this the `<img>` would stay invisible behind
  // the placeholder forever and we'd never record the natural aspect.
  useEffect(() => {
    const img = ref.current;
    if (!img) return;
    if (img.complete && img.naturalWidth > 0) {
      recordAspect(state.save.id, img.naturalWidth, img.naturalHeight);
      setLoaded(true);
    }
  }, [state.save.id]);

  return (
    <>
      <Backdrop blur={blur} tint={tint} />
      <img
        ref={ref}
        src={url}
        alt=""
        loading="lazy"
        decoding="async"
        width={w}
        height={h}
        className={styles.media}
        data-loaded={loaded ? "true" : "false"}
        onLoad={(e) => {
          const img = e.currentTarget;
          recordAspect(state.save.id, img.naturalWidth, img.naturalHeight);
          setLoaded(true);
        }}
        onError={() => actions.setBroken(true)}
      />
    </>
  );
}

/**
 * Painted behind the lazy-loaded `<img>`. When we have a stored
 * blur preview (`Save.blurDataUrl`, generated by the colors
 * enrichment job), render it as a real `<img>` and lean on a CSS
 * blur filter — same shape as Next.js `placeholder="blur"`. Falls
 * back to the dominant cover colour, then a neutral gradient.
 *
 * Kept as a sibling of `<img>` (not as a backdrop on the parent)
 * because the slot is already absolutely-positioned by the packer
 * and we want a stable z-stack: backdrop at z=0, image at z=1.
 */
function Backdrop({
  blur,
  tint,
}: {
  blur: string | null;
  tint: string | undefined;
}) {
  if (blur) {
    return (
      <span className={styles["backdrop-blur"]} aria-hidden>
        <img src={blur} alt="" decoding="sync" />
      </span>
    );
  }
  return (
    <span
      className={styles.tint}
      style={tint ? { background: tint } : undefined}
      aria-hidden
    />
  );
}
