import { useCallback, useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  Button,
  Collapsible,
  CollapsiblePanel,
  CollapsibleTrigger,
  Field,
  FieldDescription,
  FieldLabel,
  Input,
  NumberField,
  useToast,
} from "../../ui";
import styles from "./styles.module.css";

type BackfillSource = "twitter";

interface BackfillEntry {
  state: "idle" | "running" | "done" | "error" | "auth_required";
  message?: string;
  progress?: { current: number; total: number };
  lastSyncedAt: string | null;
}

const BACKFILL_SOURCES: ReadonlyArray<{ id: BackfillSource; label: string }> = [
  { id: "twitter", label: "Twitter / X bookmarks" },
];

/**
 * First-run onboarding. Three beats:
 *
 *  1. "Here's your ingest token" -- copy to clipboard.
 *  2. "Install the browser extension" -- link to the store page (or
 *     `chrome://extensions` for side-load).
 *  3. "You're done" -- send user to the library view.
 *
 * The token is generated by the main process on first launch; we just
 * pull it via `window.pond.query('settings.ingestToken')`.
 */
export function WelcomePage() {
  const nav = useNavigate();
  const toast = useToast();
  const [token, setToken] = useState<string | null>(null);
  const [pairing, setPairing] = useState<string | null>(null);
  const [port, setPort] = useState<number>(41610);

  useEffect(() => {
    void (async () => {
      const t = (await window.pond.query("settings.ingestToken")) as {
        token: string | null;
      };
      setToken(t.token ?? null);
      if (t.token) {
        const url = new URL("pond://pair");
        url.searchParams.set("port", String(port));
        url.searchParams.set("token", t.token);
        setPairing(url.toString());
      }
    })();
  }, [port]);

  async function copy(text: string, what: string) {
    await navigator.clipboard.writeText(text);
    toast.add({ title: `Copied ${what}`, type: "success" });
  }

  async function markOnboarded() {
    await window.pond.query("settings.markOnboarded", { value: true });
    nav("/");
  }

  return (
    <div className={styles.welcome}>
      <h2>Welcome to pond</h2>
      <p className={styles.lead}>
        A local archive for the stuff you save. Everything lives on your machine
        — no cloud, no accounts.
      </p>

      <ol className={styles.steps}>
        <li>
          <h3>Install the browser extension</h3>
          <p>
            Install from the Chrome / Firefox store. If you're a developer, load{" "}
            <code>apps/extension</code> as an unpacked extension.
          </p>
        </li>

        <li>
          <h3>Pair it with this app</h3>
          <p>Click the pond icon in your browser, paste the pairing link:</p>
          <Field>
            <FieldLabel className={styles.srOnly}>Pairing link</FieldLabel>
            <div className={styles.row}>
              <Input
                variant="code"
                readOnly
                value={pairing ?? "generating…"}
                onFocus={(e) => e.currentTarget.select()}
              />
              <Button
                disabled={!pairing}
                onClick={() => pairing && copy(pairing, "pairing link")}
              >
                Copy link
              </Button>
            </div>
          </Field>

          <Collapsible>
            <CollapsibleTrigger>Or copy token manually</CollapsibleTrigger>
            <CollapsiblePanel>
              <div className={styles.tokenRow}>
                <code>{token ?? "…"}</code>
                <Button
                  size="sm"
                  disabled={!token}
                  onClick={() => token && copy(token, "token")}
                >
                  Copy token
                </Button>
              </div>
              <p className={styles.hint}>
                Endpoint: <code>http://127.0.0.1:{port}/api/v2/item/add</code>
              </p>
              <Field>
                <FieldLabel>Port</FieldLabel>
                <NumberField
                  value={port}
                  onValueChange={(v) => setPort(v ?? 41610)}
                  min={1024}
                  max={65535}
                />
                <FieldDescription>
                  Change only if 41610 is taken on your machine.
                </FieldDescription>
              </Field>
            </CollapsiblePanel>
          </Collapsible>
        </li>

        <li>
          <h3>Save something</h3>
          <p>
            Right-click any page and pick "Save this page to pond" — it'll
            appear in your library within a second.
          </p>
        </li>

        <li>
          <h3>Backfill from connected sources</h3>
          <p>
            Already have bookmarks elsewhere? Connect a source from{" "}
            <strong>Settings → Connected accounts</strong> and Pond will scrape
            your full history into the local library.
          </p>
          <BackfillPanel />
        </li>
      </ol>

      <div className={styles.done}>
        <Button variant="primary" size="lg" onClick={markOnboarded}>
          I'm set up → Open library
        </Button>
      </div>
    </div>
  );
}

/**
 * First-run backfill panel. One row per supported list-harvest source —
 * fires `syncSource(<src>, { mode: "backfill" })` on click and renders
 * progress via `IPC.syncStatus`. Sources the user hasn't connected yet
 * get a "Connect first" CTA so the button can't no-op silently.
 */
function BackfillPanel() {
  const toast = useToast();
  const [connections, setConnections] = useState<
    Partial<Record<BackfillSource, boolean>>
  >({});
  const [entries, setEntries] = useState<
    Partial<Record<BackfillSource, BackfillEntry>>
  >({});

  const refreshStatus = useCallback(async (src: BackfillSource) => {
    const s = await window.pond.syncStatus(src).catch(() => null);
    if (!s?.ok) return;
    setEntries((prev) => ({
      ...prev,
      [src]: {
        state: s.running ? "running" : "idle",
        lastSyncedAt: s.lastSyncedAt ?? null,
      },
    }));
  }, []);

  useEffect(() => {
    let active = true;
    void (async () => {
      for (const { id } of BACKFILL_SOURCES) {
        const r = await window.pond.sourceStatus(id).catch(() => null);
        if (!active) return;
        setConnections((prev) => ({
          ...prev,
          [id]: r?.ok ? r.connected : false,
        }));
        await refreshStatus(id);
      }
    })();
    const off = window.pond.onSyncStatus((upd) => {
      const src = BACKFILL_SOURCES.find((s) => s.id === upd.source);
      if (!src) return;
      setEntries((prev) => ({
        ...prev,
        [src.id]: {
          state: upd.state,
          message: upd.message,
          progress: upd.progress,
          lastSyncedAt: upd.lastSyncedAt ?? prev[src.id]?.lastSyncedAt ?? null,
        },
      }));
    });
    return () => {
      active = false;
      off();
    };
  }, [refreshStatus]);

  async function startBackfill(src: BackfillSource) {
    const r = await window.pond.syncRunNow(src, "backfill");
    if (!r.ok) {
      toast.add({
        title:
          r.reason === "already_running"
            ? "Backfill already running"
            : "Couldn't start backfill",
        type: r.reason === "already_running" ? "info" : "error",
      });
    }
  }

  async function connect(src: BackfillSource) {
    await window.pond.connectSource(src);
    const r = await window.pond.sourceStatus(src).catch(() => null);
    setConnections((prev) => ({
      ...prev,
      [src]: r?.ok ? r.connected : false,
    }));
  }

  return (
    <div>
      {BACKFILL_SOURCES.map(({ id, label }) => {
        const connected = connections[id];
        const entry = entries[id];
        const isRunning = entry?.state === "running";
        const pct = entry?.progress
          ? Math.min(
              100,
              Math.max(
                0,
                Math.round(
                  (entry.progress.current / Math.max(entry.progress.total, 1)) *
                    100,
                ),
              ),
            )
          : null;
        return (
          <div key={id}>
            <div className={styles.backfillRow}>
              <div className={styles.backfillLabel}>
                <span>{label}</span>
                <span className={styles.backfillStatus}>
                  {connected === false
                    ? "Not connected"
                    : entry?.state === "running"
                      ? (entry.message ?? "Syncing…")
                      : entry?.state === "error"
                        ? `Failed: ${entry.message ?? "unknown"}`
                        : entry?.state === "auth_required"
                          ? "Sign in required"
                          : entry?.lastSyncedAt
                            ? "Up to date"
                            : "Ready"}
                </span>
              </div>
              {connected === false ? (
                <Button size="sm" onClick={() => void connect(id)}>
                  Connect
                </Button>
              ) : (
                <Button
                  size="sm"
                  disabled={isRunning}
                  onClick={() => void startBackfill(id)}
                >
                  {isRunning ? "Running…" : "Backfill all"}
                </Button>
              )}
            </div>
            {pct !== null ? (
              <div className={styles.backfillBar}>
                <span
                  className={styles.backfillBarFill}
                  style={{ width: `${pct}%` }}
                />
              </div>
            ) : null}
          </div>
        );
      })}
    </div>
  );
}
