import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import {
  Button,
  Collapsible,
  CollapsiblePanel,
  CollapsibleTrigger,
  Field,
  FieldDescription,
  FieldLabel,
  Input,
  NumberField,
  useToast,
} from "../../ui";
import styles from "./styles.module.css";

/**
 * First-run onboarding. Three beats:
 *
 *  1. "Here's your ingest token" -- copy to clipboard.
 *  2. "Install the browser extension" -- link to the store page (or
 *     `chrome://extensions` for side-load).
 *  3. "You're done" -- send user to the library view.
 *
 * The token is generated by the main process on first launch; we just
 * pull it via `window.pond.query('settings.ingestToken')`.
 */
export function WelcomePage() {
  const nav = useNavigate();
  const toast = useToast();
  const [token, setToken] = useState<string | null>(null);
  const [pairing, setPairing] = useState<string | null>(null);
  const [port, setPort] = useState<number>(41610);

  useEffect(() => {
    void (async () => {
      const t = (await window.pond.query("settings.ingestToken")) as {
        token: string | null;
      };
      setToken(t.token ?? null);
      if (t.token) {
        const url = new URL("pond://pair");
        url.searchParams.set("port", String(port));
        url.searchParams.set("token", t.token);
        setPairing(url.toString());
      }
    })();
  }, [port]);

  async function copy(text: string, what: string) {
    await navigator.clipboard.writeText(text);
    toast.add({ title: `Copied ${what}`, type: "success" });
  }

  async function markOnboarded() {
    await window.pond.query("settings.markOnboarded", { value: true });
    nav("/");
  }

  return (
    <div className={styles.welcome}>
      <h2>Welcome to pond</h2>
      <p className={styles.lead}>
        A local archive for the stuff you save. Everything lives on your machine
        — no cloud, no accounts.
      </p>

      <ol className={styles.steps}>
        <li>
          <h3>Install the browser extension</h3>
          <p>
            Install from the Chrome / Firefox store. If you're a developer, load{" "}
            <code>apps/extension</code> as an unpacked extension.
          </p>
        </li>

        <li>
          <h3>Pair it with this app</h3>
          <p>Click the pond icon in your browser, paste the pairing link:</p>
          <Field>
            <FieldLabel className={styles.srOnly}>Pairing link</FieldLabel>
            <div className={styles.row}>
              <Input
                variant="code"
                readOnly
                value={pairing ?? "generating…"}
                onFocus={(e) => e.currentTarget.select()}
              />
              <Button
                disabled={!pairing}
                onClick={() => pairing && copy(pairing, "pairing link")}
              >
                Copy link
              </Button>
            </div>
          </Field>

          <Collapsible>
            <CollapsibleTrigger>Or copy token manually</CollapsibleTrigger>
            <CollapsiblePanel>
              <div className={styles.tokenRow}>
                <code>{token ?? "…"}</code>
                <Button
                  size="sm"
                  disabled={!token}
                  onClick={() => token && copy(token, "token")}
                >
                  Copy token
                </Button>
              </div>
              <p className={styles.hint}>
                Endpoint: <code>http://127.0.0.1:{port}/api/v2/item/add</code>
              </p>
              <Field>
                <FieldLabel>Port</FieldLabel>
                <NumberField
                  value={port}
                  onValueChange={(v) => setPort(v ?? 41610)}
                  min={1024}
                  max={65535}
                />
                <FieldDescription>
                  Change only if 41610 is taken on your machine.
                </FieldDescription>
              </Field>
            </CollapsiblePanel>
          </Collapsible>
        </li>

        <li>
          <h3>Save something</h3>
          <p>
            Right-click any page and pick "Save this page to pond" — it'll
            appear in your library within a second.
          </p>
        </li>
      </ol>

      <div className={styles.done}>
        <Button variant="primary" size="lg" onClick={markOnboarded}>
          I'm set up → Open library
        </Button>
      </div>
    </div>
  );
}
